Forum/urls.py
from django.urls import path
from Forum import views

app_name = 'Forum'
urlpatterns = [
    path('', views.home, name='home'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('topics/<int:pk>/', views.topic_posts, name='topic_posts'),
    path('topics/<int:pk>/reply/', views.reply_topic, name='reply'),
]

JobRecruitment/urls.py
from django.contrib import admin

from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings

from UserAuth import views

urlpatterns = [
    path("", include('Forum.urls')),
    # path("", views.index),
    path("admin/", admin.site.urls),
    path("auth/", include("UserAuth.urls")),
    path("info/", include("UserInfo.urls")),
    path("position/", include("PublishPosition.urls")),
    path("mdeditor/", include("mdeditor.urls")),
    path("application/", include("Application.urls")),
    path("message/", include("UserMessage.urls")),

    re_path(r'media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
]

UserInfo/urls.py
from django.urls import path
from UserInfo import views
from UserAuth import views as auth_model

app_name = "UserInfo"
urlpatterns = [
    path("index/<int:pk>/", views.index, name='index'),
    path("resume/", views.resume, name="resume"),
    path("application/", views.apply, name='application'),
    path("myposition/", views.my_published_position, name='my_position'),
    path("info/", views.info, name='user_info'),
    path("account/", views.account, name='account'),
    path("logout/", auth_model.logout),
    path("modify/", views.modify, name='modify'),
    path("upload/", views.image_upload, name='image_upload'),
    path("resume_upload/", views.resume_upload, name="resume_upload"),
    path("resume_download/", views.resume_download),
    path('resume_remove/<int:rid>/', views.remove_resume, name="resume_remove"),
    path('show_index/', views.show_index),
    path('sendemail/', views.sendemail),
]

UserInfo/models.py
from django.db import models

from UserAuth.models import User


class Resume(models.Model):
    name = models.CharField(verbose_name="简历名称", max_length=40)
    file_path = models.CharField(verbose_name="简历路径", max_length=200)
    belong_to = models.ForeignKey(verbose_name="所属用户", to=User, to_field='id',on_delete=models.CASCADE)

    def __str__(self):
        return "{}的简历：{}".format(self.belong_to.username, self.name)

UserInfo/views.py
import datetime
import os
import re

from django.shortcuts import render, redirect, HttpResponse
from django.http import JsonResponse
from django.core.paginator import Paginator, EmptyPage
from django.conf import settings
import urllib.parse
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import ValidationError

from UserAuth.utils.generateCode import send_sms_code
from UserAuth.utils import validators
from UserAuth.utils.encrypt import rsa_decrypt_password
from UserAuth.models import User
from Application.models import Application
from PublishPosition.models import Position
from UserInfo.models import Resume


# Create your views here.
def index(request, pk):
    pattern = re.compile(str(request.session['UserInfo'].get("id")) + r'.*')
    matching_files = find_image(request)

    # 查询并返回数据
    query_set = User.objects.filter(id=pk)
    # 获取用户数据
    obj = query_set.first()

    topic_per_page = 5
    topic = obj.topics.order_by('last_updated')
    topic_paginator = Paginator(topic, topic_per_page)
    topic_page_number = request.GET.get('topic_page')
    show_topic_page = topic_page_number is not None
    try:
        topic_current_page = topic_paginator.get_page(topic_page_number)
    except EmptyPage:
        topic_current_page = topic_paginator.page(topic_paginator.num_pages)

    is_hr = obj.hr_allowed == 3  # 具有HR资格就要显示其发布的岗位

    user_info = {
        "id": pk,
        "username": obj.username,
        "mobile_phone": obj.mobile_phone,
        "gender": obj.get_gender_display(),
        "email": obj.email,
        "edu_ground": obj.edu_ground,
        "school": obj.school,
        "major": obj.major,
        "excepting_position": obj.excepting_position,
        "excepting_location": obj.excepting_location,
        "matching_files": matching_files,
        'topics': topic_current_page,
        'show_position': show_topic_page,
        'initial_position': request.GET.get('scrollPosition'),
        'scroll_to_bottom': show_topic_page,
        'is_hr': is_hr,
    }

    if is_hr:
        position_per_page = 6
        position = obj.positions.filter(published_state=1)
        position_paginator = Paginator(position, position_per_page)
        position_page_number = request.GET.get('position_page')
        show_position_page = position_page_number is not None
        try:
            position_current_page = position_paginator.get_page(position_page_number)
        except EmptyPage:
            position_current_page = position_paginator.page(position_paginator.num_pages)

        scroll_to_bottom = show_topic_page or show_position_page

        user_info['scroll_to_bottom'] = scroll_to_bottom
        user_info['positions'] = position_current_page
        user_info['show_position'] = show_position_page

    return render(request, "UserInfo/index.html", context=user_info)


def resume(request):
    # 查询当前用户的所有简历
    current_user_obj = User.objects.filter(id=request.session.get("UserInfo").get("id")).first()
    resume_query_set = Resume.objects.filter(belong_to=current_user_obj)
    resume_list = []
    for resume_obj in resume_query_set:
        resume_list.append({
            "id": resume_obj.id,
            "name": resume_obj.name
        })
    context = {"resumes": resume_list}
    return render(request, "UserInfo/resume.html", context=context)


def apply(request):
    """查看申请历史记录"""
    # 获取用户信息
    user_obj = User.objects.filter(id=request.session.get('UserInfo').get("id")).first()
    # 筛选用户申请记录
    position_query_set = Application.objects.filter(applicant=user_obj, active_state=1)
    # 转化为列表供前端渲染
    position_list = []
    for obj in position_query_set:
        list_obj = {
            'position_id': obj.position.id,
            'position_name': obj.position.position_name,
            'application_time': (obj.application_time + datetime.timedelta(hours=8)).strftime(
                "%Y-%m-%d %H:%M"),
        }
        position_list.append(list_obj)

    context = {
        'position_list': position_list,
    }

    return render(request, 'UserInfo/user_application.html', context)


def account(request):
    """修改用户敏感数据"""
    # 获取用户对象
    user_obj = User.objects.filter(id=request.session.get("UserInfo").get("id")).first()

    if request.method == 'GET':
        data_dict = {
            'username': user_obj.username,
            'mobile_phone': user_obj.mobile_phone,
            'email': user_obj.email,
            'identity': user_obj.get_identity_display()
        }
        context = {
            'data_dict': data_dict
        }
        return render(request, "UserInfo/user_account.html", context=context)

    # else POST
    error_dict = {}
    fields = ['username', 'password', 'confirm_password', 'mobile_phone', 'email', 'verification_code']
    post_data = {}
    for field in fields:
        post_data[field] = request.POST.get(field)
    # 校验字段值
    check_passed = True
    # check username 唯一性/不包含特殊字符
    user_query_set = User.objects.filter(username=post_data['username'])
    if user_query_set and user_query_set.first().id != user_obj.id:
        # 存在其他用户具有相同的用户名
        error_dict['username'] = "用户名已存在"
        check_passed = False
    if not validators.is_username_valid(post_data['username']):
        error_dict['username'] = "用户名只能包含数字和字母"
        check_passed = False

    # # check password and confirm_password
    # if post_data['password'] or post_data['confirm_password']:
    #     if post_data['password'] != post_data['confirm_password']:
    #         error_dict['confirm_password'] = "两次密码不一致"
    #         check_passed = False

    new_password = post_data['password']

    # check mobile_phone and email
    if not validators.is_valid_email(post_data['email']):
        error_dict['email'] = "非法的邮箱格式"
        check_passed = False
    if not validators.is_mobile_phone_valid(post_data['mobile_phone']):
        error_dict['mobile_phone'] = "非法的手机号格式"
        check_passed = False

    # check verification_code
    if post_data['verification_code'] != request.session.get("account_verification_code"):
        error_dict['verification_code'] = "验证码错误"
        check_passed = False

    if not check_passed:
        return render(request, "UserInfo/user_account.html", {"data_dict": post_data, "error_dict": error_dict})

    # ready to save
    save_data = {
        'username': post_data['username'],
        'mobile_phone': post_data['mobile_phone'],
        'email': post_data['email']
    }

    # 解密new_password为哈希值
    new_password_hash = rsa_decrypt_password(new_password)
    try:
        str_decoded_password_hash = new_password_hash.decode('latin1')
    except:
        raise ValidationError("哈希值转字符串失败，请联系管理员")

    if str_decoded_password_hash:
        save_data['password'] = str_decoded_password_hash
    print(save_data)
    User.objects.filter(id=request.session.get("UserInfo").get("id")).update(**save_data)
    return redirect("/info/info/")


@csrf_exempt
def sendemail(request):
    if not request.method == "POST":
        return JsonResponse({
            'state': False,
            'msg': "Invalid request method!"
        })

    # else POST
    user_obj = User.objects.filter(id=request.session.get("UserInfo").get("id")).first()
    new_email = request.POST.get("new_email_address")
    data_dict = {}
    # 发送邮箱验证码
    state, code = send_sms_code(user_obj.email)
    if not state:
        data_dict['state'] = False
        data_dict['msg'] = '邮件发送失败，请稍后重试'

    # state = True
    request.session['account_verification_code'] = code
    request.session.set_expiry(5 * 60)  # 5分钟有效期
    data_dict['state'] = True
    if user_obj.email == new_email:
        data_dict['msg'] = "邮件已发送至{}".format(user_obj.email)
    else:
        data_dict['msg'] = "此次修改设置了新邮箱{}，请注意检查！".format(new_email)

    return JsonResponse(data_dict)


def image_upload(request):
    if request.method == 'POST':
        upload_image = request.FILES.get('upload')
        if not upload_image:
            return render(request, 'UserInfo/upload_avatar_result.html', {'message': '没有上传头像', 'success': False})
        # 获取上传文件的后缀名
        file_extension = os.path.splitext(upload_image.name)[1]
        # 这里对文件后缀名进行检验、设置白名单
        white_list = {'.jpg', '.png', '.jpeg', '.gif', '.bmp', '.tiff', '.svg'}
        if file_extension not in white_list:
            return render(request, 'UserInfo/upload_avatar_result.html',
                          {'message': '你上传的文件格式不正确', 'success': False})
        # 将原有图像进行删除
        pattern = re.compile(str(request.session['UserInfo'].get("id")) + r'.*')
        file_names = os.listdir(settings.PROFILE_ROOT)
        matching_files = []
        for file_name in file_names:
            if pattern.match(file_name):
                matching_files.append(file_name)
                os.remove(settings.PROFILE_ROOT + file_name)
        save_path = os.path.join(settings.PROFILE_ROOT, str(request.session['UserInfo'].get("id")) + file_extension)
        # 保存文件到指定位置
        with open(save_path, 'wb') as file:
            for chunk in upload_image.chunks():
                file.write(chunk)
        return render(request, 'UserInfo/upload_avatar_result.html', {'message': '头像上传成功', 'success': True})
    else:
        return render(request, 'UserInfo/upload_avatar_result.html', {'message': '头像上传失败', 'success': False})


def modify(request):
    # 获取当前用户数据行
    query_set = User.objects.filter(id=request.session['UserInfo'].get("id"))
    # 正常来说根据id查表应该查询出唯一的用户，这里作检查
    if len(query_set) != 1:
        return HttpResponse("不合法的身份")
    # 获取用户数据
    obj = query_set.first()
    user_info = {"id": request.session['UserInfo'].get("id"),
                 "username": obj.username,
                 "mobile_phone": obj.mobile_phone,
                 "gender": obj.get_gender_display(),
                 "email": obj.email,
                 "edu_ground": obj.edu_ground,
                 "school": obj.school,
                 "major": obj.major,

UserInfo/templates/UserInfo/alert_page.html
{% extends 'base.html' %}

{% load static static_tags humanize %}

{% block title %}提示{% endblock %}

{% block content %}
<div class="alert alert-danger" role="alert" style="text-align: center">
    <h1>{{ msg }}</h1>
    <h3><a href="/">返回主页</a></h3>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

{% block js %}
<script src="{% static 'js/jquery-3.6.0.min.js' %}" nonce="{{request.csp_nonce}}"></script>
{% endblock %}

UserInfo/templates/UserInfo/resume.html
{% extends 'base.html' %}

{% load static widget_tweaks %}

{% block title %}个人简历{% endblock %}


{% block stylesheet %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
    <style nonce="{{request.csp_nonce}}">

        .left-nav {
            background-color: #17a2b8;
            color: white;
        }

        .custom-nav .nav-link {
            height: 60px;
            line-height: 20px;
            text-overflow: ellipsis;
            overflow: hidden;
            white-space: nowrap;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .custom-nav .nav-link:hover {
            background-color: rgba(255, 255, 255, 0.1);
            color: white;
            border-radius: 5px;
        }

        .custom-nav .nav-link.active {
            background-color: rgba(255, 255, 255, 0.3);
            color: white;
            border-radius: 5px;
        }

        .divider {
            border-top: 1px solid white;
            margin-top: 8px;
            margin-bottom: 8px;
        }

        .upload-button {
            background-color: #17a2b8;
            color: white;
            border: 1px solid white;
            height: 55px;
            display: flex;
            align-items: center;
            justify-content: center;
        }


        .full-width-nav {
            position: fixed;
            margin-top: 50px;
            top: 0;
            left: 0;
            height: 100%;
            background-color: #17a2b8;
            color: white;
            z-index: 0;
        }

        #myModal {
            display: none;
            position: fixed;
            z-index: 1;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
            background-color: rgba(0, 0, 0, 0.6);
        }

        #resumeModal {
            position: relative;
            height: 80px;
            background-color: #fff;
            border: 0px solid #000;
            padding: 20px;
        }


        .modal {
            position: fixed;
            top: 35%;
            left: 50%;
            transform: translate(-50%, -50%);
            border: 1px solid #888;
            color: #000;
        }


        .modal-content {
            background-color: #fefefe;
            margin: auto;
            margin-top: 170px;
            padding: 20px;
            border: 1px solid #888;
            width: 50%;
        }

        .close {
            color: #aaa;
            float: right;
            font-size: 28px;
            font-weight: bold;
        }

        .close:hover,
        .close:focus {
            color: black;
            text-decoration: none;
            cursor: pointer;
        }


        #uploadedResume {
            width: 100%;
            height: 100%;
            object-fit: contain;
        }

        .modal,
        #modalBackdrop {
            display: none;
        }

        #modalBackdrop {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(128, 128, 128, 0.6);
            z-index: 0;
        }

        .nav-item-left {
            width: 100%;
            text-overflow: ellipsis;
            white-space: nowrap;
            overflow: hidden;
        }


    </style>
{% endblock %}


{% block content %}
    <div class="container-fluid">
        <div class="row">
            <nav class="d-md-block sidebar left-nav full-width-nav" style="width: 20%;">
                <div class="position-sticky">
                    <a class="btn btn-primary w-100 mb-2 upload-button"
                       style="font-weight: bold; margin-top: 40px;" id="uploadResumeBtn" onclick="openModal()"><i
                            style="font-size: 1.5rem;"
                            class="bi bi-cloud-upload"></i>&nbsp;&nbsp;上传新简历</a>

                    <div id="myModal" class="modal">
                        <div class="modal-content">
                            <span class="close" onclick="closeModal()" id="closeModalBtn">&times;</span>
                            <h2 style="text-align: center;">请选择您要上传的简历文件</h2>
                            <p style="text-align: center; color: #17a2b8; font-weight: bold;">
                                文件格式必须以.pdf为后缀</p>
                            <form method="post" action="{% url 'UserInfo:resume_upload' %}"
                                  enctype="multipart/form-data"
                                  class="d-flex justify-content-center align-items-center flex-wrap">
                                {% csrf_token %}
                                <div class="form-group">
{#                                    <label for="resume_name" class="custom-text-color">简历名称</label>#}
                                    <input type="text" id="resume_name" name="resume_name"
                                    class="form-control" placeholder="简历名称" required>
                                </div>
                                <div class="form-group">
                                    <label class="btn btn-primary custom-button" style="margin:20px;">
                                        选择简历文件
                                        <input type="file" name="upload" accept=".pdf" id="fileInput"
                                               style="display: none;">
                                    </label>
                                </div>
                                <button type="submit" class="btn btn-primary custom-button" style="margin:20px;">确认上传
                                </button>
                            </form>

                            <div class="row">
                                <div id="resumeModal" class="col-md-12">
                                    <p id="uploadedResume" style="text-align: center; font-weight: bold;"></p>
                                </div>
                                <div style="padding: 40px; text-align: center;">
                                    <div id="noResumeText">您还没有上传简历</div>
                                </div>
                                <div id="uploadMessage" style="display: none;"></div>
                            </div>
                        </div>
                    </div>
                    <div id="modalBackdrop" class="modal-backdrop"></div>


                    <hr class="divider">
                    <ul class="nav flex-column custom-nav">
                        {% for resume in resumes %}
                            <li class="nav-item nav-item-left" style="display: flex; align-items: center;">
                                <a class="nav-link text-white" style="margin-left: auto; margin-right: auto;" href="#resume{{ forloop.counter }}"
                                   data-toggle="collapse"
                                   id="resume_clicked{{ forloop.counter }}"
                                   onclick="toggleNavColor('resume_clicked{{ forloop.counter }}')">
                                    {{ resume.name }}
                                </a>

                                <a href="{% url 'UserInfo:resume_remove' resume.id %}" class="btn btn-warning custom-button" style="margin-left: auto">删除</a>
                            </li>
                            <script nonce="{{request.csp_nonce}}">
                                var myBox = document.getElementById('resume_clicked{{ forloop.counter }}');
                                var text = myBox.innerText;
                                var maxLength = 15;
                                if (text.length > maxLength) {
                                    text = text.substring(0, maxLength) + '...';
                                }
                                myBox.innerText = text;
                            </script>
                            <hr class="divider">
                        {% endfor %}
                    </ul>
                </div>
            </nav>


            <main class="px-md-4" style="width: 90%; padding-top:10px; margin-left:15%">
                {% for resume in resumes %}
                    <div id="resume{{ forloop.counter }}" class="collapse resume-content">
                        <embed src="../resume_download?resume_id={{ resume.id }}" type="application/pdf" width="100%"
                               height="600">
                    </div>
                {% endfor %}
            </main>


        </div>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

{% block js %}
    <script nonce="{{request.csp_nonce}}">


        document.getElementById("uploadResumeBtn").addEventListener("click", openModal);
        document.getElementById("fileInput").addEventListener("change", handleFileSelect);


        function openModal() {
            console.log('Upload button clicked!');

            var modal = document.getElementById("myModal");
            var modalBackdrop = document.getElementById("modalBackdrop");

            if (modal && modalBackdrop) {
                modal.style.display = "block";
                modalBackdrop.style.display = "block";
                resumeModal.style.display = "none";
                noResumeText.style.display = "block";

                var closeBtn = document.getElementById("closeModalBtn");
                closeBtn.addEventListener("click", closeModal);
            } else {
                console.error("modal or modalBackdrop element not found.");
            }
        }

        function closeModal() {
            var modal = document.getElementById("myModal");
            var modalBackdrop = document.getElementById("modalBackdrop");
            modal.style.display = "none";
            modalBackdrop.style.display = "none";
            resumeModal.style.display = "none";
            noResumeText.style.display = "none";
        }


        function handleFileSelect(event) {

            const fileInput = event.target;
            const selectedFile = fileInput.files[0];
            const uploadedResume = document.getElementById("uploadedResume");
            const noResumeText = document.getElementById("noResumeText");


            if (selectedFile) {
                const reader = new FileReader();

                reader.onload = function (event) {
                    resumeModal.style.display = "block";
                    noResumeText.style.display = "none";
                    uploadedResume.textContent = "已选择文件：" + selectedFile.name;
                    document.getElementById("resumeModal").style.display = "block";
                };

                reader.readAsDataURL(selectedFile);
            } else {
                resumeModal.style.display = "none";
                noResumeText.style.display = "block";
                selectedResumeFilename.textContent = "";
                document.getElementById("resumeModal").style.display = "block";
            }
        }


        function toggleNavColor(targetId) {

            var targetNavItem = document.getElementById(targetId);
            var isCurrentlyActive = targetNavItem.classList.contains('active');
            var navItems = document.querySelectorAll('.nav-link');

            var currentActiveResume = document.querySelector('.resume-content.show');
            var resumeContentId = targetId.replace('resume_clicked', 'resume');
            var resumeContent = document.getElementById(resumeContentId);

            if (currentActiveResume) {
                currentActiveResume.classList.remove('show');
            }

            navItems.forEach(function (item) {
                item.classList.remove('active');
            });

            if (!isCurrentlyActive) {
                console.log('Clicked: NOT ACTIVE' + targetId);

                targetNavItem.classList.add('active');
                resumeContent.classList.add('show');
            }
        }


    </script>
{% endblock %}



UserInfo/templates/UserInfo/show_index.html
{% extends 'base.html' %}

{% load static widget_tweaks %}

{% block title %}个人主页{% endblock %}

{% block stylesheet %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
    <style nonce="{{request.csp_nonce}}">

        .custom-text-color {
            color: #17a2b8 !important;
            font-weight: bold;
        }

        .custom-background{
            background-color: #E5E5E5;
        }

        .custom-button{
            background-color: #17a2b8;
            color: white;
            border: 1px solid #17a2b8;
        }
    </style>
{% endblock %}

{% block content %}

{% end block %}

UserInfo/templates/UserInfo/upload_avatar_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>头像上传结果</title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.bundle.min.js" nonce="{{request.csp_nonce}}"></script>
    <style nonce="{{request.csp_nonce}}">
        .custom-text-color {
            color: #17a2b8 !important;
            font-weight: bold;
        }

        .custom-background{
            background-color: #E5E5E5;
        }

        .custom-button{
            background-color: #17a2b8;
            color: white;
            border: 1px solid #17a2b8;
        }

        .custom-text-color{
            color: #17a2b8 !important;
        }

        .content-container {
            padding-top: 100px;
        }

        h1{
            margin: 60px;
        }

        .dropdown-container {
            position: relative;
            left: -50px;
        }


    </style>
</head>
<body class="custom-background">

<nav class="navbar navbar-expand-sm navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand custom-text-color" href="#">JobRecruitment</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">首页</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">内推</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">面经</a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<div class="content-container"></div>
<div>
    {% if success %}
    <h1 style="color: #17a2b8; text-align: center;">{{ message }}</h1>
    {% else %}
    <h1 style="color: red; text-align: center;">{{ message }}</h1>
    {% endif %}
</div>
<div style="text-align:center">
    <a href="{% url 'UserInfo:user_info' %}" class="btn btn-primary custom-button">返回个人信息</a>
</div>


<script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js" nonce="{{request.csp_nonce}}"></script>
<script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js" nonce="{{request.csp_nonce}}"></script>
<script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.min.js" nonce="{{request.csp_nonce}}"></script>

</body>
</html>

UserInfo/templates/UserInfo/upload_resume_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>头像上传结果</title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <style nonce="{{request.csp_nonce}}">
        .custom-text-color {
            color: #17a2b8 !important;
            font-weight: bold;
        }

        .custom-background{
            background-color: #E5E5E5;
        }

        .custom-button{
            background-color: #17a2b8;
            color: white;
            border: 1px solid #17a2b8;
        }

        .custom-text-color{
            color: #17a2b8 !important;
        }

        .content-container {
            padding-top: 100px;
        }

        h1{
            margin: 60px;
        }

        .dropdown-container {
            position: relative;
            left: -50px;
        }


    </style>
</head>
<body class="custom-background">

<nav class="navbar navbar-expand-sm navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand custom-text-color" href="#">JobRecruitment</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">首页</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">内推</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">面经</a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<div class="content-container"></div>
<div>
    {% if success %}
    <h1 style="color: #17a2b8; text-align: center;">{{ msg }}</h1>
    {% else %}
    <h1 style="color: red; text-align: center;">{{ msg }}</h1>
    {% endif %}
</div>
<div style="text-align:center">
    <a href="/info/resume/" class="btn btn-primary custom-button">返回我的简历</a>
</div>


<script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js" nonce="{{request.csp_nonce}}"></script>
<script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js" nonce="{{request.csp_nonce}}"></script>
<script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.bundle.min.js" nonce="{{request.csp_nonce}}"></script>

</body>
</html>