Forum/urls.py
from django.urls import path
from Forum import views

app_name = 'Forum'
urlpatterns = [
    path('', views.home, name='home'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('topics/<int:pk>/', views.topic_posts, name='topic_posts'),
    path('topics/<int:pk>/reply/', views.reply_topic, name='reply'),
]

JobRecruitment/urls.py
from django.contrib import admin

from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings

from UserAuth import views

urlpatterns = [
    path("", include('Forum.urls')),
    # path("", views.index),
    path("admin/", admin.site.urls),
    path("auth/", include("UserAuth.urls")),
    path("info/", include("UserInfo.urls")),
    path("position/", include("PublishPosition.urls")),
    path("mdeditor/", include("mdeditor.urls")),
    path("application/", include("Application.urls")),
    path("message/", include("UserMessage.urls")),

    re_path(r'media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
]

PublishPosition/urls.py
from django.urls import path

from PublishPosition import views

"""
should include:
/list   展示列表
view/<int: nid>/    查看编号为nid的岗位详情
publish/    发布职位
"""

app_name = "PublishPosition"
urlpatterns = [
    path("list/", views.position_list, name='publish_list'),
    path("view/<int:nid>/", views.view_position_detail, name='detail'),
    path("publish/", views.publish_position, name='publish'),
    path("modify/<int:nid>/", views.modify_position, name='modify_position'),
]

UserAuth/urls.py
from django.urls import path
from UserAuth import views


app_name = 'UserAuth'
urlpatterns = [
    path("login/", views.login, name='login'),
    path("register/", views.register, name='register'),
    path("reset/", views.reset_password, name='reset_password'),
    path("changeidentity/", views.change_identity),

    path("gencode/", views.generate_verification_code, name='gencode'),
    path("sendemail/", views.register_email, name='sendemail'),
    path("resetpasswordemail/", views.reset_password_email, name='reset_password_email'),

    path("state/", views.check_login_state),
    path("logout/", views.logout, name='logout'),
    path('public-key/', views.get_public_key, name='public_key'),

]

UserInfo/urls.py
from django.urls import path
from UserInfo import views
from UserAuth import views as auth_model

app_name = "UserInfo"
urlpatterns = [
    path("index/<int:pk>/", views.index, name='index'),
    path("resume/", views.resume, name="resume"),
    path("application/", views.apply, name='application'),
    path("myposition/", views.my_published_position, name='my_position'),
    path("info/", views.info, name='user_info'),
    path("account/", views.account, name='account'),
    path("logout/", auth_model.logout),
    path("modify/", views.modify, name='modify'),
    path("upload/", views.image_upload, name='image_upload'),
    path("resume_upload/", views.resume_upload, name="resume_upload"),
    path("resume_download/", views.resume_download),
    path('resume_remove/<int:rid>/', views.remove_resume, name="resume_remove"),
    path('show_index/', views.show_index),
    path('sendemail/', views.sendemail),
]

UserMessage/urls.py
from django.urls import path

from UserMessage import views

app_name = "UserMessage"
urlpatterns = [
    path("send/", views.send_message),
    path("list/", views.message_list, name="message_box"),
    path("view/<int:mid>/", views.view_message_detail)
]

templates/base.html
{% load static static_tags %}
<!DOCTYPE html>
<html lang="zh">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Django 论坛{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.bundle.min.js" nonce="{{request.csp_nonce}}"></script>
    {% block stylesheet %}{% endblock %}
    <style nonce="{{request.csp_nonce}}">
        /* 页面背景和文字自定义颜色 */
        body.custom-background {
            background-color: #dee2e6;
        }

        .custom-text-color {
            color: #17a2b8;
            /* JobRecruitment 自定义字体颜色 */
        }

        /* 按钮颜色和圆角样式 */
        .custom-button,
        .btn {
            background-color: #17a2b8;
            border: none;
            color: white;
            border-radius: 25px;
            padding: 10px 20px;
            /* 调整按钮的内边距 */
            font-size: 16px;
            /* 调整按钮字体大小 */
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
            /* 增加按钮阴影 */
            transition: all 0.3s ease;
            /* 平滑过渡效果 */
        }

        .custom-button:hover,
        .btn:hover {
            background-color: #138496;
            box-shadow: 0 6px 15px rgba(0, 0, 0, 0.2);
            transform: translateY(-2px) scale(1.05);
            /* 悬停时上移 */
        }

        .navbar-nav {
            font-family: 'Arial', sans-serif; /* 更改字体 */
            font-size: 1.1rem; /* 调整字体大小 */
        }

        .nav-link {
            color: #ffffff; /* 链接的基本颜色 */
            padding: 10px 15px; /* 内边距 */
            transition: background-color 0.3s ease, color 0.3s ease; /* 背景颜色和文字颜色变化的过渡 */
            border-radius: 0.5rem; /* 加大倒角 */
        }

        .nav-link:hover {
            background-color: #6c757d; /* 悬停时背景色 */
            color: #d4edda; /* 悬停时文字颜色 */
            transform: scale(1.05); /* 悬停时放大效果 */
        }

        .custom-nav-link {
            position: relative; /* 为伪元素定位 */
        }

        .custom-nav-link::after {
            content: ""; /* 创建一个伪元素 */
            display: block; /* 设置为块级元素 */
            height: 3px; /* 下划线的高度 */
            width: 0; /* 初始宽度为0 */
            background: #98d99e; /* 下划线颜色 */
            transition: width 0.3s; /* 宽度变化的过渡 */
            position: absolute; /* 绝对定位 */
            left: 50%; /* 向左移动50% */
            bottom: -5px; /* 向下移动5px */
        }

        .custom-nav-link:hover::after {
            width: 100%; /* 悬停时下划线宽度为100% */
            left: 0; /* 向左移动到0 */
        }


        /* 页脚样式 */
        footer {
            background-color: #343a40; /* 页脚背景颜色 */
            color: #adb5bd; /* 文字颜色 */
            padding: 20px 0; /* 增加上下内边距 */
        }

        footer a {
            color: #adb5bd; /* 链接颜色 */
            transition: color 0.3s ease; /* 添加平滑过渡 */
        }

        footer a:hover {
            color: #ffffff; /* 悬停时链接颜色 */
            text-decoration: underline; /* 悬停时添加下划线 */
        }

        /* 页脚中间对齐文本 */
        footer .row {
            justify-content: center; /* 中间对齐 */
        }

        footer h5 {
            color: #ffffff; /* 页脚标题颜色 */
            font-weight: bold; /* 加粗字体 */
            margin-bottom: 15px; /* 增加下边距 */
        }

        /* 用户头像样式 */
        .rounded-circle {
            border: 2px solid #17a2b8;
            /* 添加蓝绿色边框 */
            padding: 2px;
            /* 添加内边距 */
        }

        .dropdown-menu {
            background-color: #ffffff; /* 背景颜色 */
            border: 1px solid #dee2e6; /* 边框颜色 */
            border-radius: 0.5rem; /* 圆角 */
            box-shadow: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.1); /* 阴影效果 */
            min-width: 100px; /* 设置最小宽度 */
            width: auto; /* 允许根据内容自动调整宽度 */
            padding: 0; /* 去掉内边距 */
        }

        .dropdown-item {
            color: #343a40; /* 文字颜色 */
            padding: 10px 15px; /* 内边距 */
            transition: background-color 0.3s ease, transform 0.3s ease; /* 背景颜色变化和缩放效果的过渡 */
        }

        .dropdown-item:hover {
            background-color: #e2f0e2; /* 悬停时加深背景颜色 */
            color: #98d99e; /* 悬停时文字颜色为淡绿色 */
            text-decoration: none; /* 去掉下划线 */
            transform: scale(1.05); /* 悬停时文字放大 */
        }

        .form-control {
            border-radius: 0.75rem; /* 加大倒角 */
            border: 1px solid #17a2b8; /* 边框颜色 */
            box-shadow: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.1); /* 阴影效果 */
            transition: border-color 0.3s ease, box-shadow 0.3s ease; /* 边框颜色变化和阴影效果的过渡 */
            font-size: 1rem; /* 字体大小 */
        }

        .form-control:focus {
            border-color: #17a2b8; /* 聚焦时边框颜色 */
            box-shadow: 0 0.5rem 1rem rgba(0, 155, 70, 0.5); /* 聚焦时的阴影效果 */
            outline: none; /* 去掉默认聚焦轮廓 */
        }
    </style>
</head>

<body class="custom-background">

    {% block body %}
    <nav class="navbar navbar-expand-sm navbar-light bg-light shadow-sm">
        <div class="container">
            <a class="navbar-brand custom-text-color" href="{% url 'Forum:home' %}">JobRecruitment</a>
            <button class="navbar-toggler btn custom-button" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link custom-nav-link" href="{% url 'Forum:home' %}">首页</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link custom-nav-link" href="{% url 'PublishPosition:publish_list' %}">职位</a>
                    </li>
                </ul>
                <form class="d-flex" method="get" action="/position/list/">
                    <input class="form-control me-2" type="text" name="keyword" placeholder="搜索职位"
                        aria-label="Search">
                    <button class="btn custom-button" type="submit"><i class="fas fa-search"></i></button>
                </form>
                {% if 'UserInfo' in request.session %}
                <div class="nav-item dropdown">
                    {% with id=request.session.UserInfo.id %}
                    <a class="nav-link dropdown-toggle" href="{% url 'UserInfo:index' id %}" id="navbardrop"
                        data-bs-toggle="dropdown">
                        {% with user_id=id|stringformat:'d' %}
                        {% with user_avatar_path="images/"|add:user_id %}
                        {% query_image_extension user_avatar_path as user_avatar_full_path %}
                        {% with default_avatar_path='images/default.jpeg' %}
                        {% if user_avatar_full_path|static_file_exists %}
                        <img src="{% static user_avatar_full_path %}?rand=<%= Date.now() %>" alt="用户头像"
                            class="rounded-circle" style="width:40px; height:40px;">
                        {% else %}
                        <img src="{% static default_avatar_path %}" alt="默认头像" class="rounded-circle"
                            style="width:40px; height:40px;">
                        {% endif %}
                        {% endwith %}
                        {% endwith %}
                        {% endwith %}
                    </a>
                    {% endwith %}
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'UserInfo:resume' %}">我的简历</a>
                        <a class="dropdown-item" href="{% url 'UserInfo:application' %}">我的投递</a>
                        <a class="dropdown-item" href="{% url 'UserMessage:message_box' %}">我的收件箱</a>
                        <a class="dropdown-item" href="{% url 'UserInfo:user_info' %}">个人资料</a>
                        <a class="dropdown-item" href="{% url 'UserInfo:account' %}">账号安全</a>
                        <a class="dropdown-item" href="{% url 'UserInfo:my_position' %}">我发布的职位</a>
                        <a class="dropdown-item" href="{% url 'UserAuth:logout' %}">退出登录</a>
                    </div>
                </div>
                <div class="nav-item dropdown">
                    <button type="button" class="btn custom-button dropdown-toggle" onclick="window.location.href='#'"
                        data-bs-toggle="dropdown">
                        发布
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'Forum:new_topic' %}">发动态</a>
                        <a class="dropdown-item" href="{% url 'PublishPosition:publish'%}">发职位</a>
                    </div>
                </div>
                {% else %}
                <form class="form-inline ml-auto">
                    <a href="{% url 'UserAuth:login' %}" class="btn btn-outline-secondary">登录</a>
                    <a href="{% url 'UserAuth:register' %}" class="btn custom-button ml-2">注册</a>
                </form>
                {% endif %}
            </div>
        </div>
    </nav>

    <div class="container mb-5">
        {% block content %}
        {% endblock %}
    </div>

    {% block footer %}
    <footer class="py-4">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h5>联系方式</h5>
                    <ul class="list-unstyled">
                        <li>电话：XXX-XXXX-XXXX</li>
                        <li>邮件：example@qq.com</li>
                        <li>地址：上海市闵行区东川路800号</li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <h5>导航</h5>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'Forum:home' %}" class="text-decoration-none">首页</a></li>
                        <li><a href="#" class="text-decoration-none">关于我们</a></li>
                        <li><a href="#" class="text-decoration-none">服务</a></li>
                        <li><a href="#" class="text-decoration-none">联系我们</a></li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <h5>社交媒体</h5>
                    <ul class="list-unstyled d-flex">
                        <li class="me-3"><a href="https://www.facebook.com/" class="text-decoration-none"><i
                                    class="fab fa-facebook fa-lg"></i></a></li>
                        <li class="me-3"><a href="https://twitter.com/" class="text-decoration-none"><i
                                    class="fab fa-twitter fa-lg"></i></a></li>
                        <li><a href="https://www.instagram.com/" class="text-decoration-none"><i
                                    class="fab fa-instagram fa-lg"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js" nonce="{{request.csp_nonce}}"></script>
    <script nonce="{{request.csp_nonce}}">
        $(document).ready(function () {
            $(".dropdown").hover(function () {
                $(this).children(".dropdown-menu").toggleClass("show");
            });


        });

        $(document).ready(function () {
            $(document).off('click.bs.dropdown.data-api');
        });
    </script>

    {% block js %}{% endblock %}
    {% endblock body %}
</body>

</html>